#!/bin/bash
#
# Mac Mini Home Server Setup Script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/noble1911/home-server/main/setup.sh | bash
#
# Options:
#   --no-ssh           Skip SSH setup (if managing Mac Mini directly)
#   --drive-name=NAME  Use a different external drive name (default: HomeServer)
#   --skip-voice       Skip voice stack (if not using voice features)
#   --skip-nanobot     Skip Nanobot AI agent deployment
#

set -e

# Base URL for scripts
BASE_URL="https://raw.githubusercontent.com/noble1911/home-server/main/scripts"

# Parse arguments
ENABLE_SSH=true
DRIVE_NAME="HomeServer"
SKIP_VOICE=false
SKIP_NANOBOT=false

for arg in "$@"; do
    case $arg in
        --no-ssh)
            ENABLE_SSH=false
            ;;
        --drive-name=*)
            DRIVE_NAME="${arg#*=}"
            ;;
        --skip-voice)
            SKIP_VOICE=true
            ;;
        --skip-nanobot)
            SKIP_NANOBOT=true
            ;;
    esac
done

export DRIVE_NAME
export DRIVE_PATH="/Volumes/${DRIVE_NAME}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║            Mac Mini Home Server Setup                     ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ─────────────────────────────────────────────
# Phase 0: Credentials
# Collect all admin credentials and generate API keys upfront
# so the rest of setup runs unattended.
# ─────────────────────────────────────────────
echo -e "\n${GREEN}Phase 0: Credentials${NC}"

CREDENTIALS_FILE="$HOME/.homeserver-credentials"

if [[ -f "$CREDENTIALS_FILE" ]]; then
    echo -e "  ${GREEN}✓${NC} Credentials file exists at ${CREDENTIALS_FILE}"
    echo -e "  ${YELLOW}⚠${NC} Delete it and re-run to regenerate"
    # shellcheck disable=SC1090
    source "$CREDENTIALS_FILE"
else
    echo -e "${BLUE}==>${NC} Generating API keys for *arr apps..."
    RADARR_API_KEY=$(openssl rand -hex 16)
    SONARR_API_KEY=$(openssl rand -hex 16)
    READARR_API_KEY=$(openssl rand -hex 16)
    PROWLARR_API_KEY=$(openssl rand -hex 16)
    echo -e "  ${GREEN}✓${NC} API keys generated for Radarr, Sonarr, Readarr, Prowlarr"

    echo ""
    echo -e "${BLUE}==>${NC} App admin accounts"
    echo "  These credentials will be used to configure apps automatically."
    echo ""

    # Read from /dev/tty so prompts work even when piped via curl | bash
    read -rp "  Jellyfin admin username [admin]: " JELLYFIN_ADMIN_USER < /dev/tty
    JELLYFIN_ADMIN_USER="${JELLYFIN_ADMIN_USER:-admin}"
    read -rp "  Jellyfin admin password: " JELLYFIN_ADMIN_PASS < /dev/tty
    while [[ -z "$JELLYFIN_ADMIN_PASS" ]]; do
        echo "  Password cannot be empty."
        read -rp "  Jellyfin admin password: " JELLYFIN_ADMIN_PASS < /dev/tty
    done

    echo ""
    read -rp "  Audiobookshelf admin username [admin]: " ABS_ADMIN_USER < /dev/tty
    ABS_ADMIN_USER="${ABS_ADMIN_USER:-admin}"
    read -rp "  Audiobookshelf admin password: " ABS_ADMIN_PASS < /dev/tty
    while [[ -z "$ABS_ADMIN_PASS" ]]; do
        echo "  Password cannot be empty."
        read -rp "  Audiobookshelf admin password: " ABS_ADMIN_PASS < /dev/tty
    done

    echo ""
    read -rp "  Nextcloud admin username [admin]: " NEXTCLOUD_ADMIN_USER < /dev/tty
    NEXTCLOUD_ADMIN_USER="${NEXTCLOUD_ADMIN_USER:-admin}"
    read -rp "  Nextcloud admin password: " NEXTCLOUD_ADMIN_PASS < /dev/tty
    while [[ -z "$NEXTCLOUD_ADMIN_PASS" ]]; do
        echo "  Password cannot be empty."
        read -rp "  Nextcloud admin password: " NEXTCLOUD_ADMIN_PASS < /dev/tty
    done

    # Write credentials file (using printf to safely handle special chars in passwords)
    {
        echo "# HomeServer credentials — generated by setup.sh"
        echo "# DO NOT COMMIT THIS FILE"
        echo ""
        echo "# *arr app API keys (auto-generated)"
        printf 'RADARR_API_KEY=%s\n' "$RADARR_API_KEY"
        printf 'SONARR_API_KEY=%s\n' "$SONARR_API_KEY"
        printf 'READARR_API_KEY=%s\n' "$READARR_API_KEY"
        printf 'PROWLARR_API_KEY=%s\n' "$PROWLARR_API_KEY"
        echo ""
        echo "# Jellyfin admin"
        printf 'JELLYFIN_ADMIN_USER=%s\n' "$JELLYFIN_ADMIN_USER"
        printf 'JELLYFIN_ADMIN_PASS=%s\n' "$JELLYFIN_ADMIN_PASS"
        echo ""
        echo "# Audiobookshelf admin"
        printf 'ABS_ADMIN_USER=%s\n' "$ABS_ADMIN_USER"
        printf 'ABS_ADMIN_PASS=%s\n' "$ABS_ADMIN_PASS"
        echo ""
        echo "# Nextcloud admin"
        printf 'NEXTCLOUD_ADMIN_USER=%s\n' "$NEXTCLOUD_ADMIN_USER"
        printf 'NEXTCLOUD_ADMIN_PASS=%s\n' "$NEXTCLOUD_ADMIN_PASS"
    } > "$CREDENTIALS_FILE"
    chmod 600 "$CREDENTIALS_FILE"
    echo ""
    echo -e "  ${GREEN}✓${NC} Credentials saved to ${CREDENTIALS_FILE}"
fi

# Export for child scripts
export RADARR_API_KEY SONARR_API_KEY READARR_API_KEY PROWLARR_API_KEY
export JELLYFIN_ADMIN_USER JELLYFIN_ADMIN_PASS
export ABS_ADMIN_USER ABS_ADMIN_PASS
export NEXTCLOUD_ADMIN_USER NEXTCLOUD_ADMIN_PASS

# Phase 1: Foundation
echo -e "\n${GREEN}Phase 1: Foundation${NC}"
curl -fsSL "${BASE_URL}/01-homebrew.sh" | bash
curl -fsSL "${BASE_URL}/03-power-settings.sh" | bash

if [[ "$ENABLE_SSH" == "true" ]]; then
    curl -fsSL "${BASE_URL}/04-ssh.sh" | bash
else
    echo -e "\n${GREEN}==>${NC} Skipping SSH setup (--no-ssh flag)"
fi

curl -fsSL "${BASE_URL}/05-orbstack.sh" | bash
curl -fsSL "${BASE_URL}/06-external-drive.sh" | bash -s -- --drive-name="$DRIVE_NAME"

# Phase 2: Download Infrastructure
echo -e "\n${GREEN}Phase 2: Download Infrastructure${NC}"
curl -fsSL "${BASE_URL}/07-download-stack.sh" | bash

# Phase 3: Media Stack
echo -e "\n${GREEN}Phase 3: Media Stack${NC}"
curl -fsSL "${BASE_URL}/08-media-stack.sh" | bash

# Phase 4: Books & Audio
echo -e "\n${GREEN}Phase 4: Books & Audio${NC}"
curl -fsSL "${BASE_URL}/09-books-stack.sh" | bash

# Phase 5: Photos & Files
echo -e "\n${GREEN}Phase 5: Photos & Files${NC}"
curl -fsSL "${BASE_URL}/10-photos-files.sh" | bash

# Phase 6: Smart Home
echo -e "\n${GREEN}Phase 6: Smart Home${NC}"
curl -fsSL "${BASE_URL}/11-smart-home.sh" | bash

# Phase 7: Voice (optional)
if [[ "$SKIP_VOICE" == "false" ]]; then
    echo -e "\n${GREEN}Phase 7: Voice Stack${NC}"
    curl -fsSL "${BASE_URL}/12-voice-stack.sh" | bash
else
    echo -e "\n${YELLOW}==>${NC} Skipping voice stack (--skip-voice flag)"
fi

# Phase 8: AI Agent
if [[ "$SKIP_NANOBOT" == "false" ]]; then
    echo -e "\n${GREEN}Phase 8: AI Agent (Nanobot)${NC}"
    curl -fsSL "${BASE_URL}/13-nanobot.sh" | bash
else
    echo -e "\n${YELLOW}==>${NC} Skipping Nanobot (--skip-nanobot flag)"
fi

# Summary
echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo "Services deployed:"
echo ""
echo "  Media & Downloads:"
echo "    - Jellyfin:        http://localhost:8096"
echo "    - Radarr:          http://localhost:7878"
echo "    - Sonarr:          http://localhost:8989"
echo "    - Bazarr:          http://localhost:6767"
echo "    - Prowlarr:        http://localhost:9696"
echo "    - qBittorrent:     http://localhost:8081"
echo ""
echo "  Books:"
echo "    - Calibre-Web:     http://localhost:8083"
echo "    - Audiobookshelf:  http://localhost:13378"
echo "    - Readarr:         http://localhost:8787"
echo ""
echo "  Photos & Files:"
echo "    - Immich:          http://localhost:2283"
echo "    - Nextcloud:       http://localhost:8080"
echo ""
echo "  Smart Home:"
echo "    - Home Assistant:  http://localhost:8123"
echo ""
if [[ "$SKIP_VOICE" == "false" ]]; then
echo "  Voice:"
echo "    - LiveKit:         ws://localhost:7880"
echo "    - Kokoro TTS:      http://localhost:8880"
echo ""
fi
if [[ "$SKIP_NANOBOT" == "false" ]]; then
echo "  AI Agent:"
echo "    - Nanobot:         http://localhost:8100"
echo ""
fi
echo -e "${GREEN}Auto-configured:${NC}"
echo "  ✓ Jellyfin admin account + media libraries (Movies, TV, Music)"
echo "  ✓ Radarr/Sonarr/Readarr root folders + qBittorrent download client"
echo "  ✓ Prowlarr connected to Radarr, Sonarr, Readarr + public indexers added"
echo "  ✓ Bazarr connected to Radarr + Sonarr"
echo "  ✓ Audiobookshelf admin account + libraries (Audiobooks, eBooks)"
echo "  ✓ Nextcloud admin account"
echo "  ✓ Calibre-Web library path configured"
echo "  ✓ All *arr API keys synced to Butler"
echo ""
echo -e "${YELLOW}Still needs manual setup:${NC}"
echo ""
echo "  1. Immich: Create account at http://localhost:2283"
echo "  2. Home Assistant: Create account at http://localhost:8123"
echo "  3. Calibre-Web: Change default password (admin/admin123)"
echo "  4. Install mobile apps (Jellyfin, Immich, Audiobookshelf, Nextcloud)"
echo "  5. (Optional) Add private indexers to Prowlarr at http://localhost:9696"
echo "  6. (Optional) Set up Kindle email — see docs/kindle-email-setup.md"
echo ""
if [[ "$SKIP_NANOBOT" == "false" ]]; then
echo "  7. Access Butler PWA at http://localhost:3000"
if [[ "$SKIP_VOICE" == "false" ]]; then
echo "     See docs/VOICE_ARCHITECTURE.md for voice integration details"
fi
echo ""
fi
echo -e "${YELLOW}Credentials saved to:${NC} ~/.homeserver-credentials"
echo ""
