#!/bin/bash
#
# Mac Mini Home Server Setup Script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/noble1911/home-server/main/setup.sh | bash
#
# Options:
#   --no-ssh           Skip SSH setup (if managing Mac Mini directly)
#   --drive-name=NAME  Use a different external drive name (default: HomeServer)
#   --skip-voice       Skip voice stack (if not using voice features)
#   --skip-butler      Skip Butler API deployment
#   --skip-drive       Skip external drive setup (use internal SSD)
#

set -e

# Base URL for scripts
BASE_URL="https://raw.githubusercontent.com/noble1911/home-server/main/scripts"

# Parse arguments
ENABLE_SSH=true
DRIVE_NAME="HomeServer"
SKIP_VOICE=false
SKIP_BUTLER=false
SKIP_DRIVE=false

for arg in "$@"; do
    case $arg in
        --no-ssh)
            ENABLE_SSH=false
            ;;
        --drive-name=*)
            DRIVE_NAME="${arg#*=}"
            ;;
        --skip-voice)
            SKIP_VOICE=true
            ;;
        --skip-butler)
            SKIP_BUTLER=true
            ;;
        --skip-drive)
            SKIP_DRIVE=true
            ;;
    esac
done

export DRIVE_NAME
export DRIVE_PATH="/Volumes/${DRIVE_NAME}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Run a remote script (for self-contained foundation scripts 01-06).
run_remote() {
    local url="$1"
    shift
    local tmp
    tmp=$(mktemp)
    curl -fsSL "$url" -o "$tmp"
    chmod +x "$tmp"
    bash "$tmp" "$@" < /dev/tty
    rm -f "$tmp"
}

# Run a local script from the cloned repo (for scripts 07+ that need sibling files).
run_local() {
    local script="$1"
    shift
    bash "$script" "$@" < /dev/tty
}

echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║            Mac Mini Home Server Setup                     ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ─────────────────────────────────────────────
# Phase 0: Credentials
# Collect all admin credentials and generate API keys upfront
# so the rest of setup runs unattended.
# ─────────────────────────────────────────────
echo -e "\n${GREEN}Phase 0: Credentials${NC}"

CREDENTIALS_FILE="$HOME/.homeserver-credentials"

if [[ -f "$CREDENTIALS_FILE" ]]; then
    echo -e "  ${GREEN}✓${NC} Credentials file exists at ${CREDENTIALS_FILE}"
    echo -e "  ${YELLOW}⚠${NC} Delete it and re-run to regenerate"
    # shellcheck disable=SC1090
    source "$CREDENTIALS_FILE"
else
    echo -e "${BLUE}==>${NC} Generating API keys for *arr apps..."
    RADARR_API_KEY=$(openssl rand -hex 16)
    SONARR_API_KEY=$(openssl rand -hex 16)
    READARR_API_KEY=$(openssl rand -hex 16)
    PROWLARR_API_KEY=$(openssl rand -hex 16)
    echo -e "  ${GREEN}✓${NC} API keys generated for Radarr, Sonarr, Readarr, Prowlarr"

    echo ""
    echo -e "${BLUE}==>${NC} App admin accounts"
    echo "  These credentials will be used to configure apps automatically."
    echo ""

    # Read from /dev/tty so prompts work even when piped via curl | bash
    read -rp "  Jellyfin admin username [admin]: " JELLYFIN_ADMIN_USER < /dev/tty
    JELLYFIN_ADMIN_USER="${JELLYFIN_ADMIN_USER:-admin}"
    read -rp "  Jellyfin admin password: " JELLYFIN_ADMIN_PASS < /dev/tty
    while [[ -z "$JELLYFIN_ADMIN_PASS" ]]; do
        echo "  Password cannot be empty."
        read -rp "  Jellyfin admin password: " JELLYFIN_ADMIN_PASS < /dev/tty
    done

    echo ""
    read -rp "  Audiobookshelf admin username [admin]: " ABS_ADMIN_USER < /dev/tty
    ABS_ADMIN_USER="${ABS_ADMIN_USER:-admin}"
    read -rp "  Audiobookshelf admin password: " ABS_ADMIN_PASS < /dev/tty
    while [[ -z "$ABS_ADMIN_PASS" ]]; do
        echo "  Password cannot be empty."
        read -rp "  Audiobookshelf admin password: " ABS_ADMIN_PASS < /dev/tty
    done

    echo ""
    read -rp "  Nextcloud admin username [admin]: " NEXTCLOUD_ADMIN_USER < /dev/tty
    NEXTCLOUD_ADMIN_USER="${NEXTCLOUD_ADMIN_USER:-admin}"
    read -rp "  Nextcloud admin password: " NEXTCLOUD_ADMIN_PASS < /dev/tty
    while [[ -z "$NEXTCLOUD_ADMIN_PASS" ]]; do
        echo "  Password cannot be empty."
        read -rp "  Nextcloud admin password: " NEXTCLOUD_ADMIN_PASS < /dev/tty
    done

    # Write credentials file (using printf to safely handle special chars in passwords)
    {
        echo "# HomeServer credentials — generated by setup.sh"
        echo "# DO NOT COMMIT THIS FILE"
        echo ""
        echo "# *arr app API keys (auto-generated)"
        printf 'RADARR_API_KEY=%s\n' "$RADARR_API_KEY"
        printf 'SONARR_API_KEY=%s\n' "$SONARR_API_KEY"
        printf 'READARR_API_KEY=%s\n' "$READARR_API_KEY"
        printf 'PROWLARR_API_KEY=%s\n' "$PROWLARR_API_KEY"
        echo ""
        echo "# Jellyfin admin"
        printf 'JELLYFIN_ADMIN_USER=%s\n' "$JELLYFIN_ADMIN_USER"
        printf 'JELLYFIN_ADMIN_PASS=%s\n' "$JELLYFIN_ADMIN_PASS"
        echo ""
        echo "# Audiobookshelf admin"
        printf 'ABS_ADMIN_USER=%s\n' "$ABS_ADMIN_USER"
        printf 'ABS_ADMIN_PASS=%s\n' "$ABS_ADMIN_PASS"
        echo ""
        echo "# Nextcloud admin"
        printf 'NEXTCLOUD_ADMIN_USER=%s\n' "$NEXTCLOUD_ADMIN_USER"
        printf 'NEXTCLOUD_ADMIN_PASS=%s\n' "$NEXTCLOUD_ADMIN_PASS"
    } > "$CREDENTIALS_FILE"
    chmod 600 "$CREDENTIALS_FILE"
    echo ""
    echo -e "  ${GREEN}✓${NC} Credentials saved to ${CREDENTIALS_FILE}"
fi

# Export for child scripts
export RADARR_API_KEY SONARR_API_KEY READARR_API_KEY PROWLARR_API_KEY
export JELLYFIN_ADMIN_USER JELLYFIN_ADMIN_PASS
export ABS_ADMIN_USER ABS_ADMIN_PASS
export NEXTCLOUD_ADMIN_USER NEXTCLOUD_ADMIN_PASS

# Phase 1: Foundation (self-contained scripts, fetched via curl)
echo -e "\n${GREEN}Phase 1: Foundation${NC}"
run_remote "${BASE_URL}/01-homebrew.sh"
run_remote "${BASE_URL}/03-power-settings.sh"

if [[ "$ENABLE_SSH" == "true" ]]; then
    run_remote "${BASE_URL}/04-ssh.sh"
else
    echo -e "\n${GREEN}==>${NC} Skipping SSH setup (--no-ssh flag)"
fi

run_remote "${BASE_URL}/05-orbstack.sh"
if [[ "$SKIP_DRIVE" == "false" ]]; then
    run_remote "${BASE_URL}/06-external-drive.sh" --drive-name="$DRIVE_NAME"
else
    echo -e "\n${YELLOW}==>${NC} Skipping external drive setup (--skip-drive flag)"
    # Use a local directory so downstream scripts that reference DRIVE_PATH still work
    DRIVE_PATH="$HOME/HomeServer"
    export DRIVE_PATH
    mkdir -p "$DRIVE_PATH"/{Media/{Movies,TV,Anime,Music},Books/{eBooks,Audiobooks},Photos/Immich/{library,upload,thumbs},Documents/Nextcloud,Downloads/{Complete/{Movies,TV,Anime,Books},Incomplete},Backups/{Databases,Configs}}
    echo -e "  Using ${DRIVE_PATH} on internal SSD instead"
fi

# Clone repo — scripts 07+ need sibling files (docker-compose, configs, lib/)
REPO_DIR="$HOME/home-server"
echo -e "\n${BLUE}==>${NC} Cloning repo for local scripts..."
if [[ -d "$REPO_DIR/.git" ]]; then
    git -C "$REPO_DIR" pull --ff-only 2>&1 || echo -e "  ${YELLOW}⚠${NC} Could not pull latest"
    echo -e "  ${GREEN}✓${NC} Repo up to date at ${REPO_DIR}"
else
    git clone https://github.com/noble1911/home-server.git "$REPO_DIR"
    echo -e "  ${GREEN}✓${NC} Repo cloned to ${REPO_DIR}"
fi
SCRIPTS_DIR="$REPO_DIR/scripts"

# Phase 2: Download Infrastructure (local scripts from cloned repo)
echo -e "\n${GREEN}Phase 2: Download Infrastructure${NC}"
run_local "${SCRIPTS_DIR}/07-download-stack.sh"

# Phase 3: Media Stack
echo -e "\n${GREEN}Phase 3: Media Stack${NC}"
run_local "${SCRIPTS_DIR}/08-media-stack.sh"

# Phase 4: Books & Audio
echo -e "\n${GREEN}Phase 4: Books & Audio${NC}"
run_local "${SCRIPTS_DIR}/09-books-stack.sh"

# Phase 5: Photos & Files
echo -e "\n${GREEN}Phase 5: Photos & Files${NC}"
run_local "${SCRIPTS_DIR}/10-photos-files.sh"

# Phase 6: Smart Home
echo -e "\n${GREEN}Phase 6: Smart Home${NC}"
run_local "${SCRIPTS_DIR}/11-smart-home.sh"

# Phase 7: Voice (optional)
if [[ "$SKIP_VOICE" == "false" ]]; then
    echo -e "\n${GREEN}Phase 7: Voice Stack${NC}"
    run_local "${SCRIPTS_DIR}/12-voice-stack.sh"
else
    echo -e "\n${YELLOW}==>${NC} Skipping voice stack (--skip-voice flag)"
fi

# Phase 8: Butler API
if [[ "$SKIP_BUTLER" == "false" ]]; then
    echo -e "\n${GREEN}Phase 8: Butler API${NC}"
    run_local "${SCRIPTS_DIR}/13-butler.sh"
else
    echo -e "\n${YELLOW}==>${NC} Skipping Butler API (--skip-butler flag)"
fi

# Summary
echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo "Services deployed:"
echo ""
echo "  Media & Downloads:"
echo "    - Jellyfin:        http://localhost:8096"
echo "    - Radarr:          http://localhost:7878"
echo "    - Sonarr:          http://localhost:8989"
echo "    - Bazarr:          http://localhost:6767"
echo "    - Prowlarr:        http://localhost:9696"
echo "    - qBittorrent:     http://localhost:8081"
echo ""
echo "  Books:"
echo "    - Calibre-Web:     http://localhost:8083"
echo "    - Audiobookshelf:  http://localhost:13378"
echo "    - Readarr:         http://localhost:8787"
echo ""
echo "  Photos & Files:"
echo "    - Immich:          http://localhost:2283"
echo "    - Nextcloud:       http://localhost:8080"
echo ""
echo "  Smart Home:"
echo "    - Home Assistant:  http://localhost:8123"
echo ""
if [[ "$SKIP_VOICE" == "false" ]]; then
echo "  Voice:"
echo "    - LiveKit:         ws://localhost:7880"
echo "    - Kokoro TTS:      http://localhost:8880"
echo ""
fi
if [[ "$SKIP_BUTLER" == "false" ]]; then
echo "  Butler API:"
echo "    - Butler API:      http://localhost:8000"
echo ""
fi
echo -e "${GREEN}Auto-configured:${NC}"
echo "  ✓ Jellyfin admin account + media libraries (Movies, TV, Music)"
echo "  ✓ Radarr/Sonarr/Readarr root folders + qBittorrent download client"
echo "  ✓ Prowlarr connected to Radarr, Sonarr, Readarr + public indexers added"
echo "  ✓ Bazarr connected to Radarr + Sonarr"
echo "  ✓ Audiobookshelf admin account + libraries (Audiobooks, eBooks)"
echo "  ✓ Nextcloud admin account"
echo "  ✓ Calibre-Web library path configured"
echo "  ✓ All *arr API keys synced to Butler"
echo ""
echo -e "${YELLOW}Still needs manual setup:${NC}"
echo ""
echo "  1. Immich: Create account at http://localhost:2283"
echo "  2. Home Assistant: Create account at http://localhost:8123"
echo "  3. Calibre-Web: Change default password (admin/admin123)"
echo "  4. Install mobile apps (Jellyfin, Immich, Audiobookshelf, Nextcloud)"
echo "  5. (Optional) Add private indexers to Prowlarr at http://localhost:9696"
echo "  6. (Optional) Set up Kindle email — see docs/kindle-email-setup.md"
echo ""
if [[ "$SKIP_BUTLER" == "false" ]]; then
echo "  7. Access Butler PWA at http://localhost:3000"
if [[ "$SKIP_VOICE" == "false" ]]; then
echo "     See docs/VOICE_ARCHITECTURE.md for voice integration details"
fi
echo ""
fi
echo -e "${YELLOW}Credentials saved to:${NC} ~/.homeserver-credentials"
echo ""
echo -e "${GREEN}Updating services:${NC}"
echo "  cd ~/home-server && git pull"
echo "  Then rebuild the stack you changed, e.g.:"
echo "    docker compose -f docker/media-stack/docker-compose.yml up -d --build"
echo ""
